config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to:'tops#index'
  resources :clients
  resources :forms, only:[:new, :create, :edit, :update]
  resources :addinfos, only:[:new, :create, :edit, :update]
  resources :tasks, only:[:index, :new, :create, :destroy]
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  before_action :authenticate_user!
  def index
    get_today
    @task = Task.new
    @client = Client.where(user_id: current_user.id)
  end

  private
  def get_today
    wdays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']
    @todays_wday = Date.today.wday
    wday_num = @todays_wday

    @todays_date = Date.today
    @todays_task = []

    tasks = Task.where(date: @todays_date)
    today_tasks = []
    client_id = []

    task = tasks.map do |task|
        today_tasks.push(task.task)
    end
    cid = tasks.map do |cid|
      client_id.push(cid.client_id)
    end
    
    wday_num = Date.today.wday
    if wday_num >= 7
      wday_num = wday_num - 7
    end

    day = { month: (@todays_date).month, date: (@todays_date).day, tasks: today_tasks, wday: wdays[wday_num], cid: client_id}
    @todays_task.push(day)
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/_a-header.html.erb
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
    <%# <link rel="stylesheet" href="tops.scss"> %>
    <%# <link rel="stylesheet" href="tops.css"> %>
    <%# <link rel="stylesheet" href="image.css"> %>
    
  </head>
  <body>
    <header>
      <h1>
        <a class="apps-name" href="/">tsk</a>
      </h1>
      <nav class="pc-nav">
        <ul>
          <% if user_signed_in? %>
            <%# <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
            <li><%= link_to 'logout', destroy_user_session_path, method: :delete, class: "btn-b" %></li> 
          <% else %>
            <li><%= link_to 'Login', new_user_session_path, method: :get, class: "btn-b" %></li>
            <li><%= link_to '新規登録',  new_user_registration_path, method: :get, class: "btn-b" %></li>
          <% end %>
        </ul>
      </nav>
    </header>
  </body>
</html>

app/views/tops/index.html.erb
<%= render "a-header"%>
<div class="contents">
  <div class="indexs">
    <div class="client-index">
      <%= link_to '顧客一覧', clients_path, method: :get, class: "btn-a" %>
    </div>
    <div class="task-index">
      <%= link_to 'タスク', new_task_path, method: :get, class: "btn-a" %>
    </div>
  </div>
  <% @todays_task.each do |day| %>
  <div class='today-item'>
    <div class='date'>
      <%= day[:month] %>/<%= day[:date] %> <%= day[:wday]%>
    </div>
    <div class='content'>
      <% day[:tasks].zip(day[:cid]).each do |task, cid| %>
        <% @c = Client.find_by(id: cid) %>
        <% if @c.user_id == current_user.id %>
          <div class='plan-list'>
            <%=link_to client_path(@c.id), method: :get, class:"c-link" do %><%= "#{@c.last_name}様: " %><%end%>
            <%= task %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>