config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to:'tops#index'
  resources :clients
  resources :forms, only:[:new, :create, :edit, :update]
  resources :addinfos, only:[:new, :create, :edit, :update]
  resources :tasks, only:[:index, :new, :create, :destroy]
end

app/models/client.rb
class Client < ApplicationRecord
  default_scope -> { order(last_kana: :asc) }

  belongs_to :user, optional: true
  has_one :addinfo, dependent: :destroy
  has_many :tasks, dependent: :destroy

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]+\z/, message: '全角文字を使用してください' } do
    validates :last_name
    validates :first_name
  end
  with_options presence: true, format: { with: /\A[ァ-ン]+\z/, message: '全角カタカナを使用してください' } do
    validates :last_kana
    validates :first_kana
  end

  validates :phone_num,     format: { with: /\A[0-9]+\z/ } , length: { maximum: 11}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, uniqueness: true, presence: true, format: {with: VALID_EMAIL_REGEX}

  validates :post_num, allow_blank: true, format: {with: /\A[0-9]+\z/ }

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_client, except: [:index, :new, :create]
  

  def index
    @allclients = Client.all.order('last_kana ASC')
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.valid?
      @client.save
      redirect_to clients_path
    else
      render :new
    end
  end

  def show
    get_next
    get_before
    @form = Form.find_by(user_id: current_user.id)
    @addinfo = Addinfo.find_by(client_id: @client.id)
    @allforms = Form.all
    @allinfos = Addinfo.all
    @judg_f = form_judg
    @judg_i = addinfo_judg
    get_week
    @task = Task.new
  end

  def edit
  end

  def update
    if @client.update(client_params)
      redirect_to client_path
    else
      render :edit
    end
  end

  def destroy
    @client.destroy if current_user.id == @client.user_id
    redirect_to clients_path
  end


  private
   
  def client_params
    params.require(:client).permit(:last_name, :first_name, :last_kana, :first_kana, :email, :phone_num, :birthday, :post_num, :prefecture, :city, :details, :build_num, :post_num).merge(user_id: current_user.id)
  end

  def get_client
    @client = Client.find(params[:id])
  end

  def form_judg
    return true unless @form.nil?
    return false if @form.nil?
  end

  def addinfo_judg
    return true unless @addinfo.nil?
    return false if @addinfo.nil?
  end

  def task_params
    params.require(:task).permit(:date, :task, :wday)
  end

  def get_week
    wdays = ['(日)','(月)','(火)','(水)','(木)','(金)','(土)']

    @todays_wday = Date.today.wday
    wday_num = @todays_wday

    @todays_date = Date.today
    @week_days = []

    tasks = Task.where(date: @todays_date..@todays_date + 6)

    7.times do |x|
      today_tasks = []
      tasks_id = []

      task = tasks.map do |task|
        today_tasks.push(task.task) if task.date == @todays_date + x
      end
      ids = tasks.map do |ids|
        tasks_id.push(ids.client_id) if ids.date == @todays_date + x
      end

      wday_num = Date.today.wday  + x
      if wday_num >= 7
        wday_num = wday_num - 7
      end
      days = { month: (@todays_date + x).month, date: (@todays_date+x).day, tasks: today_tasks, wday: wdays[wday_num], ids: tasks_id }

      @week_days.push(days)
    end
  end
  def get_next
    @cbox = Client.where(user_id: current_user.id).order(['field(user_id, ?)', current_user.id])
    @cbox.each_with_index do |cid, num|
      unless num == @cbox.size - 1
        if cid.id == @client.id
          @n_num = num
        end
          @next_num = @n_num.to_i + 1
          @next_id = @cbox[@next_num]
          @next_client = Client.find_by(id: @next_id)
      end
    end
  end
  def get_before
    @cbox = Client.where(user_id: current_user.id).order(['field(user_id, ?)', current_user.id])
    @cbox.each_with_index do |cid, num|
      unless num == 0
        if cid.id == @client.id
          @b_num = num
        end
          @before_num = @b_num.to_i - 1
          @before_id = @cbox[@before_num]
          @before_client = Client.find_by(id: @before_id)
      end
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<%= render "tops/a-header" %>

<div class="child-a">
  <h3 class="text-title">基本情報の編集</h3>
</div>

<div class="child-d">
    <div class="back-index">
      <%= link_to '一覧に戻る', clients_path, method: :get, class: "btn-d" %>
    </div>
</div>
<div class=" child-c">
  <%= form_with model: @client, url: client_path(@client), method: :put, class:"new-client-form", local: true do |f| %>
    <table>
      <%= render 'shared/error_messages', model: f.object %>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">お名前(全角)</label>
          <%# <span class="indispensable">必須</span> %>
        </div>
        <div class='input-name-wrap'>
          <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 山田" %>
          <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 太郎" %>
        </div>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">お名前カナ(全角)</label>
          <%# <span class="indispensable">必須</span> %>
        </div>
        <div class='input-name-wrap'>
          <%= f.text_area :last_kana, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダ" %>
          <%= f.text_area :first_kana, class:"input-name", id:"first-name-kana", placeholder:"例) タロウ" %>
        </div>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <%# <span class="indispensable">必須</span> %>
        </div>
        <%= f.text_field :phone_num, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">メールアドレス</label>
          <%# <span class="indispensable">必須</span> %>
        </div>
        <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">生年月日</label>
          <%# <span class="form-any">任意</span> %>
        </div>
        <div class='input-birth-wrap'>
          <%= raw sprintf(
                      f.date_select(
                        :birthday,
                        class:'select-birth',
                        id:"birth-date",
                        use_month_numbers: true,
                        prompt:'--',
                        start_year: 1930,
                        end_year: (Time.now.year - 5),
                        date_separator: '%s'),
                      "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
        </div>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <%# <span class="form-any">任意</span> %>
        </div>
        <%= f.text_field :post_num, class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <%# <span class="form-any">任意</span> %>
        </div>
        <%= f.text_field :prefecture, class:"input-default", id:"prefecture", placeholder:"例）東京県"%>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <%# <span class="form-any">任意</span> %>
        </div>
        <%= f.text_field :city, class:"input-default", id:"city", placeholder:"例）中央区"%>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <%# <span class="form-any">任意</span> %>
        </div>
        <%= f.text_field :details, class:"input-default", id:"addresses", placeholder:"例）1-1-1"%>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <%# <span class="form-any">任意</span> %>
        </div>
        <%= f.text_field :build_num, class:"input-default", id:"building", placeholder:"例）ビル701"%>

        <%= f.submit "保存" ,class:"btn-n" %>
    </table>
  <% end %>
  </div>
  <div class="destroy-btn">
    <%= button_to '顧客の削除', client_path(@client), method: :delete, class: "btn-o", id:"delete-btn" %>
    <div class="delete-alert hidden", id="alert" >
      この顧客に関する登録情報、タスクなどのあらゆる情報は削除されます。
    </div>
  </div>
</div>

app/views/clients/index.html.erb
<div class="parent">
  <%= render "tops/a-header"%>

  <div class="clients-index">
    <ul class="clients">
      <div class="child-a">
        <h3 class="text-title">登録済み顧客一覧</h3>
      </div>
      <% @allclients.each do |c| %>
      <% if c.user_id == current_user.id %>
        <li class="lists" id= "lists">
          <%=link_to method: :get, class:"client-name" do %>
            <%= c.last_name %><%= " " %><%= c.first_name %>
          <% end %>
          <div class="phone-email hidden", id= "phone-email">
            <%= c.phone_num %><br><%= c.email%>
          </div>
        </li>
      <% end %>
      <% end %>
    </ul>
  </div>

  <div class="child-z">
    <%= link_to '新規顧客登録', new_client_path, method: :get, class: "btn-e" %>
  </div>
</div>

app/views/clients/new.html.erb
<%= render "tops/a-header" %>

 <div class="child-a">
  <h3 class="text-title">新規顧客登録</h3>
</div>

<%= form_with model: @client, url: clients_path(@client), method: :post, class:"new-client-form", local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <%# <span class="indispensable">必須</span> %>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 山田" %>
      <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 太郎" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <%# <span class="indispensable">必須</span> %>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_kana, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダ" %>
      <%= f.text_area :first_kana, class:"input-name", id:"first-name-kana", placeholder:"例) タロウ" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">電話番号</label>
      <%# <span class="indispensable">必須</span> %>
    </div>
    <%= f.text_field :phone_num, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <%# <span class="indispensable">必須</span> %>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <%# <span class="form-any">任意</span> %>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">郵便番号</label>
      <%# <span class="form-any">任意 ハイフンなし</span> %>
    </div>
    <%= f.text_field :post_num, class:"input-default", id:"postal-code", placeholder:"例）1234567", maxlength:"7" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">都道府県</label>
      <%# <span class="form-any">任意</span> %>
    </div>
    <%= f.text_field :prefecture, class:"input-default", id:"prefecture", placeholder:"例）東京都"%>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">市区町村</label>
      <%# <span class="form-any">任意</span> %>
    </div>
    <%= f.text_field :city, class:"input-default", id:"city", placeholder:"例）中央区"%>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">番地</label>
      <%# <span class="form-any">任意</span> %>
    </div>
    <%= f.text_field :details, class:"input-default", id:"addresses", placeholder:"例）1-1-1"%>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">建物名</label>
      <%# <span class="form-any">任意</span> %>
    </div>
    <%= f.text_field :build_num, class:"input-default", id:"building", placeholder:"例）ビル1"%>
  </div>
  
  
  <%= f.submit "新規登録" ,class:"new-client-btn" %>
<% end %>

app/views/clients/show.html.erb
<div class="parent">
  <%= render "tops/a-header" %>

  <div class="child-a">
    <h2 class="client-name">
      <ruby>
        <%= @client.last_name %><%= " " %><%= @client.first_name %>
        <rt>
          <%= @client.last_kana %><%= " " %><%= @client.first_kana %>
        </rt>
      </ruby>
    </h2>
  </div>

  <div class="child-d">
    <% unless @b_num.nil? %>
      <div class="before-client">
        <%= link_to '前の顧客に戻る', client_path(id: @before_client.id), method: :get, class: "btn-c" %>
      </div>
    <% else%>
      <div class="blank"><%= ""%></div>
    <% end %>
    <div class="back-index">
      <%= link_to '一覧に戻る', clients_path, method: :get, class: "btn-d" %>
    </div>
    <% unless @n_num.nil? %>
      <div class="next-client">
        <%= link_to '次の顧客へ進む', client_path(id: @next_client.id), method: :get, class: "btn-c" %>
      </div>
    <% else%>
      <div class="blank"><%= "" %></div>
    <% end %>
  </div>

  <div class="child-c">
    <ul class="standard-info">
      <li class="info-box">
          <div class="value-name"><%= "電話番号:"%></div>
          <div class="info-value"><%= @client.phone_num %></div>
      </li>
      <li class="info-box">
          <div class="value-name"><%= "メールアドレス:"%></div>
          <div class="info-value"><%= @client.email %></div>
      </li>
      <li class="info-box">
        <div class="value-name"><%= "生年月日:"%></div>
        <% if @client.birthday? %>
          <div class="info-value"><%= @client.birthday %></div>
        <% end %>
      </li>
      <li class="info-box">
        <div class="value-name"><%= "郵便番号:"%></div>
        <% if @client.post_num? %>
          <div class="info-value"><%= @client.post_num %></div>
        <% end %>
      </li>
      <li class="info-box">
        <div class="value-name"><%= "都道府県:"%></div>
        <% if @client.prefecture? %>
         <div class="info-value"><%= @client.prefecture %></div>
        <% end %>
      </li>
      <li class="info-box">
        <div class="value-name"><%= "市区町村:"%></div>
        <% if @client.city? %>
         <div class="info-value"><%= @client.city %></div>
        <% end %>
      </li>
      <li class="info-box">
        <div class="value-name"><%= "番地:"%></div>
        <% if @client.details? %>
          <div class="info-value"><%= @client.details %></div>
        <% end %>
      </li>
      <li class="info-box">
        <div class="value-name"><%= "建物名:"%></div>
        <% if @client.build_num? %>
          <div class="info-value"><%= @client.build_num %></div>
        <% end %>
      </li>
    </ul>

    <ul class="standard-info">
      <% unless @form.nil? %>
        <li class="info-box">
          <div class="value-name"><%= "#{@form.f_name1}" %></div>
          <div class="colon"><%= ":"%></div>
          <% unless @addinfo.nil? %>
            <% if @addinfo.client_id == @client.id %>
              <div class="info-value"><%= @addinfo.add_text1 %></div>
            <% end %>
          <% end %>
        </li>
        <li class="info-box">
          <div class="value-name"><%= "#{@form.f_name2}" %></div>
          <div class="colon"><%= ":"%></div>
          <% unless @addinfo.nil? %>
            <% if @addinfo.client_id == @client.id %>
              <div class="info-value"><%= @addinfo.add_text2 %></div>
            <% end %>
          <% end %>
        </li>
        <li class="info-box">
          <div class="value-name"><%= "#{@form.f_name3}" %></div>
          <div class="colon"><%= ":"%></div>
          <% unless @addinfo.nil? %>
            <% if @addinfo.client_id == @client.id %>
              <div class="info-value"><%= @addinfo.add_text3 %></div>
            <% end %>
          <% end %>
        </li>
        <li class="info-box">
          <div class="value-name"><%= "#{@form.f_name4}" %></div>
          <div class="colon"><%= ":"%></div>
          <% unless @addinfo.nil? %>
            <% if @addinfo.client_id == @client.id %>
              <div class="info-value"><%= @addinfo.add_text4 %></div>
            <% end %>
          <% end %>
        </li>
        <li class="info-box">
          <div class="value-name"><%= "#{@form.f_name5}" %></div>
          <div class="colon"><%= ":"%></div>
          <% unless @addinfo.nil? %>
            <% if @addinfo.client_id == @client.id %>
              <div class="info-value"><%= @addinfo.add_text5 %></div>
            <% end %>
          <% end %>
        </li>
        <li class="info-box">
          <div class="value-name"><%= "#{@form.f_name6}" %></div>
          <div class="colon"><%= ":"%></div>
          <% unless @addinfo.nil? %>
            <% if @addinfo.client_id == @client.id %>
              <div class="info-value"><%= @addinfo.add_text6 %></div>
            <% end %>
          <% end %>
        </li>
        <li class="info-box">
          <div class="value-name"><%= "#{@form.f_name7}" %></div>
          <div class="colon"><%= ":"%></div>
          <% unless @addinfo.nil? %>
            <% if @addinfo.client_id == @client.id %>
              <div class="info-value"><%= @addinfo.add_text7 %></div>
            <% end %>
          <% end %>
        </li>
        <li class="info-box">
          <div class="value-name"><%= "#{@form.f_name8}" %></div>
          <div class="colon"><%= ":"%></div>
          <% unless @addinfo.nil? %>
            <% if @addinfo.client_id == @client.id %>
              <div class="info-value"><%= @addinfo.add_text8 %></div>
            <% end %>
          <% end %>
        </li>
        <li class="info-box">
          <div class="value-name"><%= "#{@form.f_name9}" %></div>
          <div class="colon"><%= ":"%></div>
          <% unless @addinfo.nil? %>
            <% if @addinfo.client_id == @client.id %>
              <div class="info-value"><%= @addinfo.add_text9 %></div>
            <% end %>
          <% end %>
        </li>
        <li class="info-box">
          <div class="value-name"><%= "#{@form.f_name10}" %></div>
          <div class="colon"><%= ":"%></div>
          <% unless @addinfo.nil? %>
            <% if @addinfo.client_id == @client.id %>
              <div class="info-value"><%= @addinfo.add_text10 %></div>
            <% end %>
          <% end %>
        </li>
      <% end%>
    </ul>
  </div>

  <div class="btn-box">
    <div class="edit-standard">
      <%= link_to '編集', edit_client_path(@client), method: :get, class: "btn-j" %>
    </div>
    <% if @judg_f == false %>
      <%= link_to '追加フォームの作成', new_form_path(:client_info => @client), method: :get, class: "btn-l" %>
    <% elsif @judg_f == true %>
      <%= link_to 'フォーム名の編集', edit_form_path(@form.id, :client_info => @client), method: :get, class: "btn-i" %>
      <% if @judg_i == false %>
        <%= link_to '追加情報の入力', new_addinfo_path(:client_info => @client), method: :get, class: "btn-i" %>
      <% elsif @judg_i == true %>
        <%= link_to '追加情報の編集', edit_addinfo_path(@addinfo.id, :client_info => @client), method: :get, class: "btn-i" %>
      <% end %>
    <% end %>
  </div>
  <div class="task-form">
    <div class="child-e">
      <%= form_with model: @task, url: tasks_path, method: :post, class: 'form', local: true do |f| %>
        <table>
          <%= f.hidden_field :redirect, :value => 1 , class: 'lavel' %>
          <%= f.hidden_field :client_id, :value => @client.id %>
          <%= f.label :日付を選択, class: 'lavel' %>
          <%= f.date_field :date, class: 'date-select' %>
          <%= f.label :予定を入力, class: 'lavel' %>
          <%= f.text_field :task, class: 'text-input' %>
          <%= f.submit '保存', class: 'btn-m' %>
        </table>
      <% end %>
    
      <div class=shows-calendar>
        <% @week_days.each do |day| %>
          <div class='shows-item'>
            <div class='date'>
              <%= day[:month] %>/<%= day[:date] %> <%= day[:wday]%>
            </div>
            <ul class='content'>
              <% if day[:tasks].length != 0 %>
                <% day[:tasks].zip(day[:ids]).each do |task, ids| %>
                  <% if @client.id == ids %>
                    <li class='plan-list'><%= task %></li>
                  <% end %>
                <% end %>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
      <div class="btn-box-b">
        <%= link_to '全タスク', new_task_path, method: :get, class: "btn-p" %>
        <%= link_to 'タスク一覧', tasks_path, method: :get, class: "btn-p" %>
      </div>
    </div>
    </div>
  </div>
</div>