config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to:'tops#index'
  resources :clients
  resources :forms, only:[:new, :create, :edit, :update]
  resources :addinfos, only:[:new, :create, :edit, :update]
  resources :tasks, only:[:index, :new, :create, :destroy]
end

app/models/addinfo.rb
class Addinfo < ApplicationRecord
  belongs_to :client, optional: true

  with_options length: { maximum: 24} do
    validates :add_text1
    validates :add_text2
    validates :add_text3
    validates :add_text4
    validates :add_text5
    validates :add_text6
    validates :add_text7
    validates :add_text8
    validates :add_text9
    validates :add_text10
  end
end

app/controllers/addinfos_controller.rb
class AddinfosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :destoy, :edit, :update]

  def new
    @allforms = Form.all
    @addinfo = Addinfo.new
    @client = Client.find(params[:client_info])
  end

  def create
    @allforms = Form.all
    @addinfo = Addinfo.new(addinfo_params)
    @client = Client.find(addinfo_params[:client_id])
    if @addinfo.save
      redirect_to client_path(@client.id)
    else
      render :new
    end
  end

  def edit
    @form = Form.find_by(user_id: current_user.id)
    @client = Client.find(params[:client_info])
    @addinfo = Addinfo.find_by(client_id: @client.id)
  end

  def update
    @form = Form.find_by(user_id: current_user.id)
    @client = Client.find(addinfo_params[:client_id])
    @addinfo = Addinfo.find(params[:id])
    if @addinfo.update(addinfo_params)
      redirect_to client_path(@client.id)
    else
      render :edit
    end
  end

  private

  def addinfo_params
      params.require(:addinfo).permit(:add_text1, :add_text2, :add_text3, :add_text4, :add_text5, :add_text6, :add_text7, :add_text8, :add_text9, :add_text10, :client_id)
  end
end

app/helpers/add_infos_helper.rb
module AddInfosHelper
end

app/views/addinfos/edit.html.erb
<%= render "tops/a-header" %>

<div class="child-a">
      <h3 class="text-title">追加したフォームの情報を編集</h3>
</div>

<div class="gide-box">
  <div class="gide-text">
    <br>登録したい情報を24文字以内で入力してください。
  </div>
</div>

<%= form_with model: @addinfo, url: addinfo_path(@addinfo), method: :put, class:"add-form-parent", local: true do |f| %>
  <%= f.hidden_field :client_id, :value => @client.id %>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text"><%= @form.f_name1 %></label>
      <%= f.text_field :add_text1, class:"add-text-input", id:"add_text1" %>
    </div>    
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text"><%= @form.f_name2 %></label>
      <%= f.text_field :add_text2, class:"add-text-input" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text"><%= @form.f_name3 %></label>
      <%= f.text_field :add_text3, class:"add-text-input" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text"><%= @form.f_name4 %></label>
      <%= f.text_field :add_text4, class:"add-text-input" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text"><%= @form.f_name5 %></label>
      <%= f.text_field :add_text5, class:"add-text-input" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text"><%= @form.f_name6 %></label>
      <%= f.text_field :add_text6, class:"add-text-input" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text"><%= @form.f_name7 %></label>
      <%= f.text_field :add_text7, class:"add-text-input" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text"><%= @form.f_name8 %></label>
      <%= f.text_field :add_text8, class:"add-text-input" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text"><%= @form.f_name9 %></label>
      <%= f.text_field :add_text9, class:"add-text-input" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text"><%= @form.f_name10 %></label>
      <%= f.text_field :add_text10, class:"add-text-input" %>
    </div>
  </div>
  <%= f.submit "保存する" ,class:"btn-h" %>
<% end %>

app/views/addinfos/new.html.erb
<%= render "tops/a-header" %>


<div class="child-a">
      <h3 class="text-title">追加したフォームの情報を入力</h3>
</div>

<div class="gide-box">
  <div class="gide-text">
    あなたが追加したフォームへ情報を登録できます！
    <br>24文字以内で情報を入力してください。
  </div>
</div>

<%= form_with model: @addinfo, url: addinfos_path(@addinfo), method: :post, class:"add-form-parent", local: true do |f| %>
  <%= f.hidden_field :client_id, :value => @client.id %>
  <% unless @allforms.length == 0 %>
  <% @allforms.each do |fo| %>
    <% if fo.user_id == current_user.id %>
      <div class="form-group">
        <div class='form-text-wrap'>
          <% if fo.f_name1? %>
            <label class="form-text"><%= fo.f_name1 %></label>
            <%= f.text_field :add_text1, class:"add-text-input", id:"add_text1" %>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <% if fo.f_name2? %>
            <label class="form-text"><%= fo.f_name2 %></label>
            <%= f.text_field :add_text2, class:"add-text-input", id:"add_text2" %>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <% if fo.f_name3? %>
            <label class="form-text"><%= fo.f_name3 %></label>
            <%= f.text_field :add_text3, class:"add-text-input", id:"add_text3" %>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <div class='form-add-text-wrap'>
          <% if fo.f_name4? %>
            <label class="form-text"><%= fo.f_name4 %></label>
            <%= f.text_field :add_text4, class:"add-text-input", id:"add_text4" %>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <% if fo.f_name5? %>
            <label class="form-text"><%= fo.f_name5 %></label>
            <%= f.text_field :add_text5, class:"add-text-input", id:"add_text5" %>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <% if fo.f_name6? %>
            <label class="form-text"><%= fo.f_name6 %></label>
            <%= f.text_field :add_text6, class:"add-text-input", id:"add_text6" %>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <% if fo.f_name7? %>
            <label class="form-text"><%= fo.f_name7 %></label>
            <%= f.text_field :add_text7, class:"add-text-input", id:"add_text7" %>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <% if fo.f_name8? %>
            <label class="form-text"><%= fo.f_name8 %></label>
            <%= f.text_field :add_text8, class:"add-text-input", id:"add_text8" %>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <% if fo.f_name9? %>
            <label class="form-text"><%= fo.f_name9 %></label>
            <%= f.text_field :add_text9, class:"add-text-input", id:"add_text9" %>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <% if fo.f_name10? %>
            <label class="form-text"><%= fo.f_name10 %></label>
            <%= f.text_field :add_text10, class:"add-text-input", id:"add_text10" %>
          <% end %>
        </div>
      </div>
      <%= f.submit "保存する" ,class:"btn-h" %>
    <% end %>
  <% end %>
  <% end %>
<% end %>