config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to:'tops#index'
  resources :clients
  resources :forms, only:[:new, :create, :edit, :update]
  resources :addinfos, only:[:new, :create, :edit, :update]
  resources :tasks, only:[:index, :new, :create, :destroy]
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :destoy]

  def new
    @form = Form.new
  end

  def create
    @form = Form.new(form_params)
    if @form.save
      redirect_to clients_path
    else
      render :new
    end
  end

  def edit
    @form = Form.find(params[:id])
  end

  def update
    @form = Form.find(params[:id])
    if @form.update(form_params)
      redirect_to clients_path
    else
      render :edit
    end
  end

  private
  def form_params
    params.require(:form).permit(:f_name1, :f_name2,:f_name3, :f_name4,:f_name5, :f_name6,:f_name7, :f_name8,:f_name9, :f_name10).merge(user_id: current_user.id)
  end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/edit.html.erb
<%= render "tops/a-header" %>

<div class="child-a">
      <h3 class="text-title">追加フォームの名前を編集</h3>
</div>

<div class="gide-box">
  <div class="gide-text">
    <br>16文字以内でフォームの名前を決めてください。
  </div>
</div>

<%= form_with model: @form, url: form_path(@form), method: :put, class:"add-form-parent", local: true do |f| %>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム１</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name1, class:"input-name", id:"f_name1", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム２</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name2, class:"input-name", id:"f_name2", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム３</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name3, class:"input-name", id:"f_name3", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム４</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name4, class:"input-name", id:"f_name4", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム５</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name5, class:"input-name", id:"f_name5", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム６</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name6, class:"input-name", id:"f_name6", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム７</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name7, class:"input-name", id:"f_name7", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム８</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name8, class:"input-name", id:"f_name8", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム９</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name9, class:"input-name", id:"f_name9", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム１０</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name10, class:"input-name", id:"f_name10", placeholder:"例) 出身地" %>
    </div>
  </div>

  <%= f.submit "保存する" ,class:"btn-h" %>
<% end %>

app/views/forms/new.html.erb
<%= render "tops/a-header" %>


<div class="child-a">
      <h3 class="text-title">追加フォームの新規作成</h3>
</div>

<div class="gide-box">
  <div class="gide-text">
    必要に応じて入力フォームを追加できます！
    <br>フォームの追加は最大で10個まで可能です。
    <br>16文字以内でフォームの名前を決めてください。
  </div>
</div>

<%= form_with model: @form, url: forms_path(@client), method: :post, class:"add-form-parent", local: true do |f| %>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム１</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name1, class:"input-name", id:"f_name1", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム２</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name2, class:"input-name", id:"f_name2", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム３</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name3, class:"input-name", id:"f_name3", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム４</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name4, class:"input-name", id:"f_name4", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム５</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name5, class:"input-name", id:"f_name5", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム６</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name6, class:"input-name", id:"f_name6", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム７</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name7, class:"input-name", id:"f_name7", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム８</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name8, class:"input-name", id:"f_name8", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム９</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name9, class:"input-name", id:"f_name9", placeholder:"例) 出身地" %>
    </div>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">追加フォーム１０</label>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :f_name10, class:"input-name", id:"f_name10", placeholder:"例) 出身地" %>
    </div>
  </div>

  <%= f.submit "保存する" ,class:"btn-h" %>
<% end %>